name: Login Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  login-tests:
    runs-on: ubuntu-latest

    services:
      firefox:
        image: selenium/standalone-firefox:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Login tests
        run: |
          pytest tests/